title: <a href="https://github.com/himmafh/himmafh.github.io/">Himma Faicha Hubbiya</a> # your name (or website title) here
logo: "/images/PAS FOTO.JPG" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  an Undergraduate Statistics Students at Diponegoro University who interested to data analyst   
  <br><br>
  <a href="https://www.instagram.com/himmafh/">Instagram</a>  
  <br><br>
  <a href="https://www.linkedin.com/in/himma-faicha-hubbiya">LinkedIn</a> 
    <br><br>
  <a href="https://github.com/himmafh">GitHub</a> 
  
  
  
  
  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
